name: Run Automated Tests
on:
  repository_dispatch:
    types: [run-tests]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run specific test
        run: npm test tests/unit/${{ github.event.client_payload.test_file }}
      - name: Upload results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results.xml  # (Optional: JUnit output)
