name: Run Jest Tests
on: 
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Test file to execute'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run specified test
        run: npm test ${{ inputs.test_file }} -- --json > test-results.json

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: jest-results
          path: test-results.json
